/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Escolha;
import Interfaces.Escolha.CadastrarProfessor;

/**
 *
 * @author pc
 */
public class EscolhaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaProfessor
     */
    public EscolhaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadProf = new javax.swing.JButton();
        botaoConProf = new javax.swing.JButton();
        botaoAltProf = new javax.swing.JButton();
        botaoExcProf = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoCadProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadProf.setText("Cadastrar Professor");
        botaoCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadProfActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadProf);
        botaoCadProf.setBounds(60, 40, 180, 34);

        botaoConProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConProf.setText("Consultar Professor");
        botaoConProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConProfActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConProf);
        botaoConProf.setBounds(60, 80, 180, 34);

        botaoAltProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAltProf.setText("Alterar Professor");
        getContentPane().add(botaoAltProf);
        botaoAltProf.setBounds(60, 120, 180, 34);

        botaoExcProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcProf.setText("Excluir Professor");
        getContentPane().add(botaoExcProf);
        botaoExcProf.setBounds(60, 160, 180, 34);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(120, 230, 77, 31);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoLogin.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-10, -10, 320, 460);

        setSize(new java.awt.Dimension(316, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadProfActionPerformed
        CadastrarProfessor cadastrarprofessor = new CadastrarProfessor();
        cadastrarprofessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCadProfActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void botaoConProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConProfActionPerformed
        ConsultarProfessor consultarprofessor = new ConsultarProfessor();
        consultarprofessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoConProfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton botaoAltProf;
    private javax.swing.JButton botaoCadProf;
    private javax.swing.JButton botaoConProf;
    private javax.swing.JButton botaoExcProf;
    // End of variables declaration//GEN-END:variables
}
