/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Escolha;
import Interfaces.Escolha.CadastrarProfessor;

/**
 *
 * @author pc
 */
public class EscolhaAssunto extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaProfessor
     */
    public EscolhaAssunto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadAss = new javax.swing.JButton();
        botaoConAss = new javax.swing.JButton();
        botaoAltAss = new javax.swing.JButton();
        botaoExcAss = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoCadAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadAss.setText("Cadastrar Assunto");
        botaoCadAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadAssActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadAss);
        botaoCadAss.setBounds(60, 40, 180, 34);

        botaoConAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConAss.setText("Consultar Assunto");
        getContentPane().add(botaoConAss);
        botaoConAss.setBounds(60, 80, 180, 34);

        botaoAltAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAltAss.setText("Alterar Assunto");
        getContentPane().add(botaoAltAss);
        botaoAltAss.setBounds(60, 120, 180, 34);

        botaoExcAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcAss.setText("Excluir Assunto");
        getContentPane().add(botaoExcAss);
        botaoExcAss.setBounds(60, 160, 180, 34);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(120, 230, 77, 31);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoLogin.jpg"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(-10, -10, 320, 460);

        setSize(new java.awt.Dimension(316, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadAssActionPerformed
        CadastrarProfessor cadastrarprofessor = new CadastrarProfessor();
        cadastrarprofessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCadAssActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaAssunto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton botaoAltAss;
    private javax.swing.JButton botaoCadAss;
    private javax.swing.JButton botaoConAss;
    private javax.swing.JButton botaoExcAss;
    // End of variables declaration//GEN-END:variables
}
