/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Admin;

import Interfaces.CadastrarProfessor;

/**
 *
 * @author pc
 */
public class EscAssunto extends javax.swing.JInternalFrame {

    /**
     * Creates new form EscProf
     */
    public EscAssunto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadAss = new javax.swing.JButton();
        botaoConAss = new javax.swing.JButton();
        botaoAltAss = new javax.swing.JButton();
        botaoExcAss = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CRUD Assunto");
        getContentPane().setLayout(null);

        botaoCadAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadAss.setText("Cadastrar Assunto");
        botaoCadAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadAssActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadAss);
        botaoCadAss.setBounds(52, 33, 180, 34);

        botaoConAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConAss.setText("Consultar Assunto");
        getContentPane().add(botaoConAss);
        botaoConAss.setBounds(52, 73, 180, 34);

        botaoAltAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAltAss.setText("Alterar Assunto");
        getContentPane().add(botaoAltAss);
        botaoAltAss.setBounds(52, 113, 180, 34);

        botaoExcAss.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcAss.setText("Excluir Assunto");
        getContentPane().add(botaoExcAss);
        botaoExcAss.setBounds(52, 153, 180, 34);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(106, 220, 77, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoLogin.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 290, 420);

        setBounds(0, 0, 300, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadAssActionPerformed
        CadastrarProfessor cadastrarprofessor = new CadastrarProfessor();
        cadastrarprofessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCadAssActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton botaoAltAss;
    private javax.swing.JButton botaoCadAss;
    private javax.swing.JButton botaoConAss;
    private javax.swing.JButton botaoExcAss;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
