/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.Admin;

import Interfaces.CadastrarProfessor;

/**
 *
 * @author pc
 */
public class EscProf extends javax.swing.JInternalFrame {

    /**
     * Creates new form EscProf
     */
    public EscProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadProf = new javax.swing.JButton();
        botaoConProf = new javax.swing.JButton();
        botaoAltProf = new javax.swing.JButton();
        botaoExcProf = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CRUD Professor");
        getContentPane().setLayout(null);

        botaoCadProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadProf.setText("Cadastrar Professor");
        botaoCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadProfActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadProf);
        botaoCadProf.setBounds(52, 33, 180, 34);

        botaoConProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConProf.setText("Consultar Professor");
        getContentPane().add(botaoConProf);
        botaoConProf.setBounds(52, 73, 180, 34);

        botaoAltProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAltProf.setText("Alterar Professor");
        getContentPane().add(botaoAltProf);
        botaoAltProf.setBounds(52, 113, 180, 34);

        botaoExcProf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcProf.setText("Excluir Professor");
        getContentPane().add(botaoExcProf);
        botaoExcProf.setBounds(52, 153, 180, 34);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(106, 220, 77, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoLogin.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 290, 420);

        setBounds(0, 0, 300, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadProfActionPerformed
        CadastrarProfessor cadastrarprofessor = new CadastrarProfessor();
        cadastrarprofessor.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCadProfActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton botaoAltProf;
    private javax.swing.JButton botaoCadProf;
    private javax.swing.JButton botaoConProf;
    private javax.swing.JButton botaoExcProf;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
