/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.DomAdmin;

import Interfaces.*;
import DAO.Conexao;
import DAO.ProfessorDAO;
import Interfaces.DomAtor.PrincipalAdmin;
import Modelo.Professor;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author XPerience
 */
public class AlterarProfessor extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public AlterarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoProfessor = new javax.swing.JLabel();
        CodigoProfessor = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JLabel();
        txtContato = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoAlterar = new javax.swing.JButton();
        txtSexo = new javax.swing.JLabel();
        txtDisciplina = new javax.swing.JLabel();
        campoContato = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        campoDisciplina1 = new javax.swing.JTextField();
        campoDisciplina2 = new javax.swing.JTextField();
        botaoPesquisar = new javax.swing.JButton();
        campoSexo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor [Domínio do Administrador]");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtCodigoProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoProfessor.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoProfessor.setText("Digite o Código");
        jPanel2.add(txtCodigoProfessor);
        txtCodigoProfessor.setBounds(40, 30, 83, 15);
        jPanel2.add(CodigoProfessor);
        CodigoProfessor.setBounds(160, 20, 90, 30);
        jPanel2.add(campoNome);
        campoNome.setBounds(160, 100, 161, 30);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setText("Nome");
        jPanel2.add(txtNome);
        txtNome.setBounds(40, 110, 32, 15);

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setText("Login");
        jPanel2.add(txtLogin);
        txtLogin.setBounds(40, 190, 29, 15);
        jPanel2.add(campoLogin);
        campoLogin.setBounds(160, 180, 161, 30);
        jPanel2.add(campoSenha);
        campoSenha.setBounds(160, 220, 161, 30);

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setText("Senha");
        jPanel2.add(txtSenha);
        txtSenha.setBounds(40, 230, 34, 15);

        txtContato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContato.setForeground(new java.awt.Color(255, 255, 255));
        txtContato.setText("Contato");
        jPanel2.add(txtContato);
        txtContato.setBounds(40, 350, 50, 15);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(140, 420, 80, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(230, 420, 90, 30);

        botaoAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAlterar.setText("Alterar");
        botaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoAlterar);
        botaoAlterar.setBounds(40, 420, 90, 30);

        txtSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSexo.setForeground(new java.awt.Color(255, 255, 255));
        txtSexo.setText("Sexo");
        jPanel2.add(txtSexo);
        txtSexo.setBounds(40, 150, 27, 15);

        txtDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        txtDisciplina.setText("Disciplina");
        jPanel2.add(txtDisciplina);
        txtDisciplina.setBounds(40, 270, 47, 20);
        jPanel2.add(campoContato);
        campoContato.setBounds(160, 340, 160, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setText("Email");
        jPanel2.add(txtEmail);
        txtEmail.setBounds(40, 390, 27, 15);
        jPanel2.add(campoEmail);
        campoEmail.setBounds(160, 380, 160, 30);
        jPanel2.add(campoDisciplina1);
        campoDisciplina1.setBounds(160, 260, 160, 30);
        jPanel2.add(campoDisciplina2);
        campoDisciplina2.setBounds(160, 300, 160, 30);

        botaoPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cons.png"))); // NOI18N
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoPesquisar);
        botaoPesquisar.setBounds(260, 20, 60, 30);

        campoSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(campoSexo);
        campoSexo.setBounds(160, 140, 160, 30);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setText("Codigo");
        jPanel2.add(txtCodigo);
        txtCodigo.setBounds(40, 70, 50, 15);
        jPanel2.add(campoCodigo);
        campoCodigo.setBounds(160, 60, 161, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Snow.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(-80, 0, 1110, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Sobre.setText("Sobre");
        Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SobreMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarActionPerformed
        String Codigo = campoCodigo.getText();
        String Nome = campoNome.getText();
        String Sexo = campoSexo.getText();
        String Login = campoLogin.getText();
        String Senha = campoSenha.getText();
        String Disciplina1 = campoDisciplina1.getText();
        String Disciplina2 = campoDisciplina2.getText();
        String Contato = campoContato.getText();
        String Email = campoEmail.getText();
        
        if(Codigo.equals("") || Sexo.equals("") || Login.equals("") || Senha.equals("") || Disciplina1.equals("") || Disciplina2.equals("") || Contato.equals("") || Email.equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio!",
                    "QSys", JOptionPane.WARNING_MESSAGE);
        }else{
            Connection con = Conexao.AbrirConexao();
            ProfessorDAO sql = new ProfessorDAO(con);
            int cod = Integer.parseInt(Codigo);
            Professor p = new Professor();
            
            p.setCodigo(cod);
            p.setNome(Nome);
            p.setSexo(Sexo);
            p.setLogin(Login);
            p.setSenha(Senha);
            p.setDisciplina1(Disciplina1);
            p.setDisciplina2(Disciplina2);
            p.setContato(Contato);
            p.setEmail(Email);
            
            sql.Alterar_Professor(p);
            Conexao.FecharConexao(con);
            
            campoCodigo.setText("");
            campoNome.setText("");
            campoSexo.setText("");
            campoLogin.setText("");
            campoSenha.setText("");
            campoDisciplina1.setText("");
            campoDisciplina2.setText("");
            campoContato.setText("");
            campoEmail.setText("");
        }
    }//GEN-LAST:event_botaoAlterarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        PrincipalAdmin principaladmin = new PrincipalAdmin();
        principaladmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        CodigoProfessor.setText("");
        campoCodigo.setText("");
        campoNome.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
        campoDisciplina1.setText("");
        campoDisciplina2.setText("");
        campoContato.setText("");
        campoEmail.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        dispose();
    }//GEN-LAST:event_SairMouseClicked

    private void SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreMouseClicked
        JOptionPane.showMessageDialog(null, "Esta janela tem como função atualizar professores em um banco de dados.\nPara realizar essa função, selecione o professor que deseja atualizar através\nde seu código, preencha os campos que deseja alterar, que até então estão\nvazios, com suas respectivas novas informações e clique no botão Alterar.\n\nBOTÕES:\n1 - Alterar: muda todos os campos preenchidos pelas novas informações.\n2 - Limpar: limpa todos os campos.\n3 - Cancelar: fecha a janela e retorna para a tela principal.");
    }//GEN-LAST:event_SobreMouseClicked

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        String Codigo = CodigoProfessor.getText();
        Connection con = Conexao.AbrirConexao();
        ProfessorDAO sql = new ProfessorDAO(con);
        
        int cod = Integer.parseInt(Codigo);
        
        Professor p = sql.Consulta_Professor(cod);
        if( p.getCodigo() != cod){
            Conexao.FecharConexao(con);
        }
        if(Codigo.equals("")){
            JOptionPane.showMessageDialog(null, "Digite um código para atualizar",
                    "QSys", JOptionPane.WARNING_MESSAGE);
        }
        
        campoCodigo.setText("");
        campoNome.setText("");
        campoSexo.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
        campoDisciplina1.setText("");
        campoDisciplina2.setText("");
        campoContato.setText("");
        campoEmail.setText("");
        
        //InserirDados(cod);
        CodigoProfessor.setText("");
            
        campoCodigo.setText("" + p.getCodigo());
        campoNome.setText(p.getNome());
        campoSexo.setText(p.getSexo());
        campoLogin.setText(p.getLogin());
        campoSenha.setText(p.getSenha());
        campoDisciplina1.setText(p.getDisciplina1());
        campoDisciplina2.setText(p.getDisciplina2());
        campoContato.setText(p.getContato());
        campoEmail.setText(p.getEmail());
        
        Conexao.FecharConexao(con);
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoProfessor;
    private javax.swing.JLabel Fundo;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Sobre;
    private javax.swing.JButton botaoAlterar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoContato;
    private javax.swing.JTextField campoDisciplina1;
    private javax.swing.JTextField campoDisciplina2;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoSexo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCodigo;
    private javax.swing.JLabel txtCodigoProfessor;
    private javax.swing.JLabel txtContato;
    private javax.swing.JLabel txtDisciplina;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtSenha;
    private javax.swing.JLabel txtSexo;
    // End of variables declaration//GEN-END:variables
    
}