/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.DomAdmin;

import Interfaces.*;
import DAO.Conexao;
import DAO.ProfessorDAO;
import Interfaces.DomAtor.PrincipalAdmin;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author XPerience
 */
public class AlterarDisciplina extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public AlterarDisciplina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoDisciplina = new javax.swing.JLabel();
        campoCodigoProfessor = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        botaoProcurar = new javax.swing.JButton();
        campoProfessor1 = new javax.swing.JTextField();
        txtProfessores = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        campoProfessor2 = new javax.swing.JTextField();
        campoProfessor3 = new javax.swing.JTextField();
        txtno3 = new javax.swing.JLabel();
        txtno2 = new javax.swing.JLabel();
        txtno1 = new javax.swing.JLabel();
        caixaAno1 = new javax.swing.JComboBox();
        caixaAno2 = new javax.swing.JComboBox();
        caixaAno3 = new javax.swing.JComboBox();
        caixaÁrea = new javax.swing.JComboBox();
        campoCargaHorária = new javax.swing.JTextField();
        txtHoras = new javax.swing.JLabel();
        txtCargaHorária = new javax.swing.JLabel();
        txtÁrea = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor [Domínio do Administrador]");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtCodigoDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoDisciplina.setText("Código da disciplina");
        jPanel2.add(txtCodigoDisciplina);
        txtCodigoDisciplina.setBounds(40, 40, 110, 15);
        jPanel2.add(campoCodigoProfessor);
        campoCodigoProfessor.setBounds(160, 30, 90, 30);
        jPanel2.add(campoNome);
        campoNome.setBounds(160, 70, 160, 30);

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cons.png"))); // NOI18N
        jPanel2.add(botaoProcurar);
        botaoProcurar.setBounds(260, 30, 60, 30);

        campoProfessor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(campoProfessor1);
        campoProfessor1.setBounds(160, 110, 160, 30);

        txtProfessores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProfessores.setForeground(new java.awt.Color(255, 255, 255));
        txtProfessores.setText("Professor(es):");
        jPanel2.add(txtProfessores);
        txtProfessores.setBounds(40, 120, 80, 15);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setText("Nome");
        jPanel2.add(txtNome);
        txtNome.setBounds(40, 80, 32, 15);

        campoProfessor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(campoProfessor2);
        campoProfessor2.setBounds(160, 150, 160, 30);

        campoProfessor3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(campoProfessor3);
        campoProfessor3.setBounds(160, 190, 160, 30);

        txtno3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtno3.setForeground(new java.awt.Color(255, 255, 255));
        txtno3.setText("no");
        jPanel2.add(txtno3);
        txtno3.setBounds(330, 200, 14, 15);

        txtno2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtno2.setForeground(new java.awt.Color(255, 255, 255));
        txtno2.setText("no");
        jPanel2.add(txtno2);
        txtno2.setBounds(330, 160, 14, 15);

        txtno1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtno1.setForeground(new java.awt.Color(255, 255, 255));
        txtno1.setText("no");
        jPanel2.add(txtno1);
        txtno1.setBounds(330, 120, 14, 15);

        caixaAno1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaAno1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º Ano", "2º Ano", "3º Ano", "1º e 2º Ano", "1º e 3º Ano", "2º e 3º Ano", "1º, 2º e 3º Ano" }));
        caixaAno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaAno1ActionPerformed(evt);
            }
        });
        jPanel2.add(caixaAno1);
        caixaAno1.setBounds(350, 110, 130, 30);

        caixaAno2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaAno2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º Ano", "2º Ano", "3º Ano", "1º e 2º Ano", "1º e 3º Ano", "2º e 3º Ano", "1º, 2º e 3º Ano" }));
        jPanel2.add(caixaAno2);
        caixaAno2.setBounds(350, 150, 130, 30);

        caixaAno3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaAno3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º Ano", "2º Ano", "3º Ano", "1º e 2º Ano", "1º e 3º Ano", "2º e 3º Ano", "1º, 2º e 3º Ano" }));
        jPanel2.add(caixaAno3);
        caixaAno3.setBounds(350, 190, 130, 30);

        caixaÁrea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaÁrea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ciências da Natureza", "Ciências Humanas", "Curso de Agronegócio", "Curso de Eletrotécnica", "Curso de Enfermagem", "Curso de Informática", "Linguagens e Códigos", "Matemática" }));
        jPanel2.add(caixaÁrea);
        caixaÁrea.setBounds(160, 230, 161, 30);
        jPanel2.add(campoCargaHorária);
        campoCargaHorária.setBounds(160, 270, 50, 30);

        txtHoras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtHoras.setForeground(new java.awt.Color(255, 255, 255));
        txtHoras.setText("horas de aula");
        jPanel2.add(txtHoras);
        txtHoras.setBounds(220, 280, 80, 15);

        txtCargaHorária.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCargaHorária.setForeground(new java.awt.Color(255, 255, 255));
        txtCargaHorária.setText("Carga Horária");
        jPanel2.add(txtCargaHorária);
        txtCargaHorária.setBounds(40, 280, 80, 15);

        txtÁrea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtÁrea.setForeground(new java.awt.Color(255, 255, 255));
        txtÁrea.setText("Área");
        jPanel2.add(txtÁrea);
        txtÁrea.setBounds(40, 240, 25, 20);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        jPanel2.add(botaoCadastrar);
        botaoCadastrar.setBounds(40, 310, 90, 30);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(140, 310, 80, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(230, 310, 90, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Snow.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(-80, 0, 1110, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Sobre.setText("Sobre");
        Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SobreMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        dispose();
    }//GEN-LAST:event_SairMouseClicked

    private void SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreMouseClicked
        JOptionPane.showMessageDialog(null, "Esta janela tem como função atualizar disciplinas em um banco de dados.\nPara realizar essa função, selecione a disciplina que deseja atualizar através\nde seu código, preencha os campos que deseja alterar, que até então estão\nvazios, com suas respectivas novas informações e clique no botão Alterar.\n\nBOTÕES:\n1 - Alterar: muda todos os campos preenchidos pelas novas informações.\n2 - Limpar: limpa todos os campos.\n3 - Cancelar: fecha a janela e retorna para a tela principal.");
    }//GEN-LAST:event_SobreMouseClicked

    private void caixaAno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaAno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaAno1ActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoCodigoProfessor.setText("");
        campoCargaHorária.setText("");
        campoProfessor1.setText("");
        campoProfessor2.setText("");
        campoProfessor3.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Sobre;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JComboBox caixaAno1;
    private javax.swing.JComboBox caixaAno2;
    private javax.swing.JComboBox caixaAno3;
    private javax.swing.JComboBox caixaÁrea;
    private javax.swing.JTextField campoCargaHorária;
    private javax.swing.JTextField campoCodigoProfessor;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoProfessor1;
    private javax.swing.JTextField campoProfessor2;
    private javax.swing.JTextField campoProfessor3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCargaHorária;
    private javax.swing.JLabel txtCodigoDisciplina;
    private javax.swing.JLabel txtHoras;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtProfessores;
    private javax.swing.JLabel txtno1;
    private javax.swing.JLabel txtno2;
    private javax.swing.JLabel txtno3;
    private javax.swing.JLabel txtÁrea;
    // End of variables declaration//GEN-END:variables

    private void setNome(JTextField Nome) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setLogin(JTextField Login) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSenha(JPasswordField Senha) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSexo(JTextField Sexo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDisciplina1(JTextField Disciplina1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDisciplina2(JTextField Disciplina2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setContato(JTextField Contato) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setEmail(JTextField Email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setCodigo(JTextField CodigoProfessor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
