/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.Conexao;
import DAO.ProfessorDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEntrar = new javax.swing.JButton();
        imagemUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        botaoSair = new javax.swing.JButton();
        BarradeProgresso = new javax.swing.JProgressBar();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(640, 360));
        setSize(new java.awt.Dimension(640, 360));
        getContentPane().setLayout(null);

        botaoEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoEntrar);
        botaoEntrar.setBounds(220, 260, 100, 30);

        imagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.png"))); // NOI18N
        getContentPane().add(imagemUsuario);
        imagemUsuario.setBounds(260, 30, 130, 140);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("USUÁRIO");
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(220, 180, 60, 30);
        getContentPane().add(Usuario);
        Usuario.setBounds(280, 180, 150, 30);

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setText("SENHA");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(220, 220, 50, 30);
        getContentPane().add(Senha);
        Senha.setBounds(280, 220, 150, 30);

        botaoSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair);
        botaoSair.setBounds(330, 260, 100, 30);
        getContentPane().add(BarradeProgresso);
        BarradeProgresso.setBounds(220, 300, 210, 20);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Space.jpg"))); // NOI18N
        getContentPane().add(imagemFundo);
        imagemFundo.setBounds(0, 0, 640, 360);

        setSize(new java.awt.Dimension(656, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        dispose();        
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        Connection con = Conexao.AbrirConexao();
        ProfessorDAO sql = new ProfessorDAO(con);        
        String login = Usuario.getText();
        String senha = Senha.getText();
        
        if (login.equalsIgnoreCase("") || senha.equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio.","QSys", JOptionPane.WARNING_MESSAGE);
            Usuario.setText("");
            Senha.setText("");
        }else{
            if (sql.Logar(login, senha) == true){
                new Thread(){
                    public void run(){
                        for (int i = 0; i < 101; i++){
                            BarradeProgresso.setValue(i);
                            try{
                                Thread.sleep(35);
                            } catch (Exception ex){
                                ex.getMessage();
                            }
                        }
                        new Principal().setVisible(true);
                        dispose();
                    }
                }.start();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos.", "QSys", JOptionPane.ERROR_MESSAGE);
                Usuario.setText("");
                Senha.setText("");
            }
        }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarradeProgresso;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel imagemUsuario;
    private javax.swing.JLabel txtSenha;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
