/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author XPerience
 */
public class Professor extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CodigoDoProfessor = new javax.swing.JLabel();
        campoCodigoProfessor = new javax.swing.JTextField();
        botaoProcurar = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        Senha = new javax.swing.JLabel();
        Contato = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        Sexo = new javax.swing.JLabel();
        caixaSexo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        campoContato = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        Titulacoes = new javax.swing.JLabel();
        selecaoLicenciatura = new javax.swing.JCheckBox();
        selecaoBacharelado = new javax.swing.JCheckBox();
        selecaoEspecializacao = new javax.swing.JCheckBox();
        selecaoMestrado = new javax.swing.JCheckBox();
        selecaoDoutorado = new javax.swing.JCheckBox();
        selecaoPosDoutorado = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoExperiencias = new javax.swing.JTextPane();
        DiretorTurma = new javax.swing.JCheckBox();
        campoDisciplina1 = new javax.swing.JTextField();
        campoDisciplina2 = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Professor = new javax.swing.JMenu();
        Assunto = new javax.swing.JMenu();
        Disciplina = new javax.swing.JMenu();
        Questão = new javax.swing.JMenu();
        Prova = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        CodigoDoProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CodigoDoProfessor.setText("Código do professor");
        jPanel2.add(CodigoDoProfessor);
        CodigoDoProfessor.setBounds(330, 20, 109, 15);
        jPanel2.add(campoCodigoProfessor);
        campoCodigoProfessor.setBounds(450, 10, 60, 30);

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoProcurar.setText("Procurar");
        jPanel2.add(botaoProcurar);
        botaoProcurar.setBounds(520, 10, 90, 30);
        jPanel2.add(campoNome);
        campoNome.setBounds(450, 50, 161, 30);

        Nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nome.setText("Nome");
        jPanel2.add(Nome);
        Nome.setBounds(330, 60, 32, 15);

        Login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Login.setText("Login");
        jPanel2.add(Login);
        Login.setBounds(330, 140, 29, 15);
        jPanel2.add(campoLogin);
        campoLogin.setBounds(450, 130, 161, 30);
        jPanel2.add(campoSenha);
        campoSenha.setBounds(450, 170, 161, 30);

        Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Senha.setText("Senha");
        jPanel2.add(Senha);
        Senha.setBounds(330, 180, 34, 15);

        Contato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Contato.setText("Contato");
        jPanel2.add(Contato);
        Contato.setBounds(330, 300, 50, 15);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(520, 380, 90, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(520, 420, 90, 30);

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(botaoExcluir);
        botaoExcluir.setBounds(420, 420, 90, 30);

        botaoConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConsultar.setText("Consultar");
        jPanel2.add(botaoConsultar);
        botaoConsultar.setBounds(420, 380, 90, 30);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        jPanel2.add(botaoCadastrar);
        botaoCadastrar.setBounds(320, 380, 90, 30);

        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAtualizar.setText("Atualizar");
        jPanel2.add(botaoAtualizar);
        botaoAtualizar.setBounds(320, 420, 90, 30);

        Sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sexo.setText("Sexo");
        jPanel2.add(Sexo);
        Sexo.setBounds(330, 100, 27, 15);

        caixaSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        caixaSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));
        caixaSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSexoActionPerformed(evt);
            }
        });
        jPanel2.add(caixaSexo);
        caixaSexo.setBounds(450, 90, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Disciplina");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(330, 220, 47, 20);
        jPanel2.add(campoContato);
        campoContato.setBounds(450, 290, 160, 30);

        Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Email.setText("Email");
        jPanel2.add(Email);
        Email.setBounds(330, 340, 27, 15);
        jPanel2.add(campoEmail);
        campoEmail.setBounds(450, 330, 160, 30);

        Titulacoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Titulacoes.setText("Titulações:");
        jPanel2.add(Titulacoes);
        Titulacoes.setBounds(640, 10, 80, 30);

        selecaoLicenciatura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoLicenciatura.setText("Licenciatura");
        jPanel2.add(selecaoLicenciatura);
        selecaoLicenciatura.setBounds(640, 30, 100, 30);

        selecaoBacharelado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoBacharelado.setText("Bacharelado");
        jPanel2.add(selecaoBacharelado);
        selecaoBacharelado.setBounds(750, 30, 90, 30);

        selecaoEspecializacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoEspecializacao.setText("Especialização");
        jPanel2.add(selecaoEspecializacao);
        selecaoEspecializacao.setBounds(640, 70, 100, 30);

        selecaoMestrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoMestrado.setText("Mestrado");
        jPanel2.add(selecaoMestrado);
        selecaoMestrado.setBounds(750, 70, 90, 30);

        selecaoDoutorado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoDoutorado.setText("Doutorado");
        jPanel2.add(selecaoDoutorado);
        selecaoDoutorado.setBounds(640, 100, 90, 40);

        selecaoPosDoutorado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        selecaoPosDoutorado.setText("Pós-Doutorado");
        jPanel2.add(selecaoPosDoutorado);
        selecaoPosDoutorado.setBounds(750, 110, 110, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Experiências anteriores ou Currículo:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(640, 140, 200, 30);

        jScrollPane1.setViewportView(textoExperiencias);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(640, 180, 200, 230);

        DiretorTurma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DiretorTurma.setText("Diretor de Turma");
        jPanel2.add(DiretorTurma);
        DiretorTurma.setBounds(640, 420, 130, 23);
        jPanel2.add(campoDisciplina1);
        campoDisciplina1.setBounds(450, 210, 160, 30);
        jPanel2.add(campoDisciplina2);
        campoDisciplina2.setBounds(450, 250, 160, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(0, 0, 860, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Professor.setText("Professor");
        Professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorMouseClicked(evt);
            }
        });
        jMenuBar2.add(Professor);

        Assunto.setText("Assunto");
        Assunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssuntoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Assunto);

        Disciplina.setText("Disciplina");
        Disciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisciplinaMouseClicked(evt);
            }
        });
        jMenuBar2.add(Disciplina);

        Questão.setText("Questão");
        Questão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestãoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Questão);

        Prova.setText("Prova");
        Prova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvaMouseClicked(evt);
            }
        });
        jMenuBar2.add(Prova);

        Sobre.setText("Sobre");
        Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SobreMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoCodigoProfessor.setText("");
        campoNome.setText("");
        campoLogin.setText("");
        campoSenha.setText("");
        campoContato.setText("");
        campoEmail.setText("");
        textoExperiencias.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void caixaSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaSexoActionPerformed

    private void AssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssuntoMouseClicked
        Assunto assunto = new Assunto();
        assunto.setVisible(true);
        dispose();
    }//GEN-LAST:event_AssuntoMouseClicked

    private void SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreMouseClicked
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
        dispose();
    }//GEN-LAST:event_SobreMouseClicked

    private void ProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorMouseClicked
        JOptionPane.showMessageDialog(null, "Você já está nessa janela.");
    }//GEN-LAST:event_ProfessorMouseClicked

    private void DisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisciplinaMouseClicked
        Disciplina disciplina = new Disciplina();
        disciplina.setVisible(true);
        dispose();
    }//GEN-LAST:event_DisciplinaMouseClicked

    private void QuestãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestãoMouseClicked
        Questão questão = new Questão();
        questão.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuestãoMouseClicked

    private void ProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvaMouseClicked
        Prova prova = new Prova();
        prova.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProvaMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        dispose();
    }//GEN-LAST:event_SairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Assunto;
    private javax.swing.JLabel CodigoDoProfessor;
    private javax.swing.JLabel Contato;
    private javax.swing.JCheckBox DiretorTurma;
    private javax.swing.JMenu Disciplina;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Nome;
    private javax.swing.JMenu Professor;
    private javax.swing.JMenu Prova;
    private javax.swing.JMenu Questão;
    private javax.swing.JMenu Sair;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Sexo;
    private javax.swing.JMenu Sobre;
    private javax.swing.JLabel Titulacoes;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JComboBox caixaSexo;
    private javax.swing.JTextField campoCodigoProfessor;
    private javax.swing.JTextField campoContato;
    private javax.swing.JTextField campoDisciplina1;
    private javax.swing.JTextField campoDisciplina2;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox selecaoBacharelado;
    private javax.swing.JCheckBox selecaoDoutorado;
    private javax.swing.JCheckBox selecaoEspecializacao;
    private javax.swing.JCheckBox selecaoLicenciatura;
    private javax.swing.JCheckBox selecaoMestrado;
    private javax.swing.JCheckBox selecaoPosDoutorado;
    private javax.swing.JTextPane textoExperiencias;
    // End of variables declaration//GEN-END:variables
}
