/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.Conexao;
import DAO.ProfessorDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author XPerience
 */
public class Professor extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoProfessor = new javax.swing.JLabel();
        CodigoProfessor = new javax.swing.JTextField();
        botaoProcurar = new javax.swing.JButton();
        Nome = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        Login = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JLabel();
        txtContato = new javax.swing.JLabel();
        botaoLimpar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoConsultar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        txtSexo = new javax.swing.JLabel();
        txtDisciplina = new javax.swing.JLabel();
        Contato = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        txtTitulacoes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Curriculo = new javax.swing.JTextPane();
        Disciplina1 = new javax.swing.JTextField();
        Disciplina2 = new javax.swing.JTextField();
        Sexo = new javax.swing.JTextField();
        txtEspecializacao = new javax.swing.JLabel();
        Especializacao = new javax.swing.JTextField();
        txtLicenciatura = new javax.swing.JLabel();
        Licenciatura = new javax.swing.JTextField();
        txtBacharelado = new javax.swing.JLabel();
        Bacharelado = new javax.swing.JTextField();
        txtMestrado = new javax.swing.JLabel();
        Mestrado = new javax.swing.JTextField();
        txtDoutorado = new javax.swing.JLabel();
        Doutorado = new javax.swing.JTextField();
        txtPosdoutorado = new javax.swing.JLabel();
        Posdoutorado = new javax.swing.JTextField();
        txtDiretordeturma = new javax.swing.JLabel();
        Diretordeturma = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Professor = new javax.swing.JMenu();
        Assunto = new javax.swing.JMenu();
        Disciplina = new javax.swing.JMenu();
        Questão = new javax.swing.JMenu();
        Prova = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Professor");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        txtCodigoProfessor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoProfessor.setText("Código do professor");
        jPanel2.add(txtCodigoProfessor);
        txtCodigoProfessor.setBounds(330, 20, 109, 15);
        jPanel2.add(CodigoProfessor);
        CodigoProfessor.setBounds(450, 10, 60, 30);

        botaoProcurar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoProcurar.setText("Procurar");
        jPanel2.add(botaoProcurar);
        botaoProcurar.setBounds(520, 10, 90, 30);
        jPanel2.add(Nome);
        Nome.setBounds(450, 50, 161, 30);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setText("Nome");
        jPanel2.add(txtNome);
        txtNome.setBounds(330, 60, 32, 15);

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLogin.setText("Login");
        jPanel2.add(txtLogin);
        txtLogin.setBounds(330, 140, 29, 15);
        jPanel2.add(Login);
        Login.setBounds(450, 130, 161, 30);
        jPanel2.add(Senha);
        Senha.setBounds(450, 170, 161, 30);

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenha.setText("Senha");
        jPanel2.add(txtSenha);
        txtSenha.setBounds(330, 180, 34, 15);

        txtContato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtContato.setText("Contato");
        jPanel2.add(txtContato);
        txtContato.setBounds(330, 300, 50, 15);

        botaoLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });
        jPanel2.add(botaoLimpar);
        botaoLimpar.setBounds(520, 380, 90, 30);

        botaoCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar);
        botaoCancelar.setBounds(520, 420, 90, 30);

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(botaoExcluir);
        botaoExcluir.setBounds(420, 420, 90, 30);

        botaoConsultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoConsultar);
        botaoConsultar.setBounds(420, 380, 90, 30);

        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCadastrar);
        botaoCadastrar.setBounds(320, 380, 90, 30);

        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoAtualizar);
        botaoAtualizar.setBounds(320, 420, 90, 30);

        txtSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSexo.setText("Sexo");
        jPanel2.add(txtSexo);
        txtSexo.setBounds(330, 100, 27, 15);

        txtDisciplina.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDisciplina.setText("Disciplina");
        jPanel2.add(txtDisciplina);
        txtDisciplina.setBounds(330, 220, 47, 20);
        jPanel2.add(Contato);
        Contato.setBounds(450, 290, 160, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setText("Email");
        jPanel2.add(txtEmail);
        txtEmail.setBounds(330, 340, 27, 15);
        jPanel2.add(Email);
        Email.setBounds(450, 330, 160, 30);

        txtTitulacoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTitulacoes.setText("Titulações:");
        jPanel2.add(txtTitulacoes);
        txtTitulacoes.setBounds(640, 0, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Experiências anteriores ou Currículo:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(640, 140, 200, 30);

        jScrollPane1.setViewportView(Curriculo);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(640, 180, 200, 230);
        jPanel2.add(Disciplina1);
        Disciplina1.setBounds(450, 210, 160, 30);
        jPanel2.add(Disciplina2);
        Disciplina2.setBounds(450, 250, 160, 30);

        Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoActionPerformed(evt);
            }
        });
        jPanel2.add(Sexo);
        Sexo.setBounds(450, 90, 160, 30);

        txtEspecializacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEspecializacao.setText("Especialização");
        jPanel2.add(txtEspecializacao);
        txtEspecializacao.setBounds(620, 120, 80, 15);
        jPanel2.add(Especializacao);
        Especializacao.setBounds(700, 110, 30, 30);

        txtLicenciatura.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtLicenciatura.setText("Licenciatura");
        jPanel2.add(txtLicenciatura);
        txtLicenciatura.setBounds(630, 40, 70, 15);
        jPanel2.add(Licenciatura);
        Licenciatura.setBounds(700, 30, 30, 30);

        txtBacharelado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBacharelado.setText("Bacharelado");
        jPanel2.add(txtBacharelado);
        txtBacharelado.setBounds(630, 80, 70, 15);
        jPanel2.add(Bacharelado);
        Bacharelado.setBounds(700, 70, 30, 30);

        txtMestrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMestrado.setText("Mestrado");
        jPanel2.add(txtMestrado);
        txtMestrado.setBounds(740, 40, 70, 15);
        jPanel2.add(Mestrado);
        Mestrado.setBounds(810, 30, 30, 30);

        txtDoutorado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDoutorado.setText("Doutorado");
        jPanel2.add(txtDoutorado);
        txtDoutorado.setBounds(740, 80, 70, 15);
        jPanel2.add(Doutorado);
        Doutorado.setBounds(810, 70, 30, 30);

        txtPosdoutorado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPosdoutorado.setText("Pós-Doutorado");
        jPanel2.add(txtPosdoutorado);
        txtPosdoutorado.setBounds(730, 120, 90, 15);
        jPanel2.add(Posdoutorado);
        Posdoutorado.setBounds(810, 110, 30, 30);

        txtDiretordeturma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDiretordeturma.setText("Diretor de Turma");
        jPanel2.add(txtDiretordeturma);
        txtDiretordeturma.setBounds(640, 430, 100, 15);
        jPanel2.add(Diretordeturma);
        Diretordeturma.setBounds(740, 420, 30, 30);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(0, 0, 860, 460);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 460);

        Professor.setText("Professor");
        Professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorMouseClicked(evt);
            }
        });
        jMenuBar2.add(Professor);

        Assunto.setText("Assunto");
        Assunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssuntoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Assunto);

        Disciplina.setText("Disciplina");
        Disciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisciplinaMouseClicked(evt);
            }
        });
        jMenuBar2.add(Disciplina);

        Questão.setText("Questão");
        Questão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestãoMouseClicked(evt);
            }
        });
        jMenuBar2.add(Questão);

        Prova.setText("Prova");
        Prova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvaMouseClicked(evt);
            }
        });
        jMenuBar2.add(Prova);

        Sobre.setText("Sobre");
        Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SobreMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sobre);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar2.add(Sair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        CodigoProfessor.setText("");
        Nome.setText("");
        Login.setText("");
        Senha.setText("");
        Disciplina1.setText("");
        Disciplina2.setText("");
        Contato.setText("");
        Email.setText("");
        Especializacao.setText("");
        Licenciatura.setText("");
        Bacharelado.setText("");
        Mestrado.setText("");
        Doutorado.setText("");
        Posdoutorado.setText("");
        Curriculo.setText("");
        Diretordeturma.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        Principal principal = new Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void AssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssuntoMouseClicked
        Assunto assunto = new Assunto();
        assunto.setVisible(true);
        dispose();
    }//GEN-LAST:event_AssuntoMouseClicked

    private void SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreMouseClicked
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
        dispose();
    }//GEN-LAST:event_SobreMouseClicked

    private void ProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorMouseClicked
        JOptionPane.showMessageDialog(null, "Você já está nessa janela.");
    }//GEN-LAST:event_ProfessorMouseClicked

    private void DisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisciplinaMouseClicked
        Disciplina disciplina = new Disciplina();
        disciplina.setVisible(true);
        dispose();
    }//GEN-LAST:event_DisciplinaMouseClicked

    private void QuestãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestãoMouseClicked
        Questão questão = new Questão();
        questão.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuestãoMouseClicked

    private void ProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvaMouseClicked
        Prova prova = new Prova();
        prova.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProvaMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        dispose();
    }//GEN-LAST:event_SairMouseClicked

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        String codigo = CodigoProfessor.getText();
        String nome = Nome.getText();
        String login = Login.getText();
        String senha = Senha.getText();
        String sexo = Sexo.getText();
        String disciplina1 = Disciplina1.getText();
        String disciplina2 = Disciplina2.getText();
        String contato = Contato.getText();
        String email = Email.getText();
        String licenciatura = txtEspecializacao.getText();
        String bacharelado = txtLicenciatura.getText();
        String especializacao = txtEspecializacao.getText();
        String mestrado = Mestrado.getText();
        String doutorado = Doutorado.getText();
        String posdoutorado = txtPosdoutorado.getText();
        String curriculo = Curriculo.getText();
        String diretordeturma = txtDiretordeturma.getText();
                
        if(nome.equals("") || login.equals("") || senha.equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio.", "QSys", JOptionPane.WARNING_MESSAGE);
        }else{
            Connection con = Conexao.AbrirConexao();
            ProfessorDAO sql = new ProfessorDAO(con);
            Professor p = new Professor();
            
            p.setNome(nome);
            p.setLogin(login);
            p.setSenha(senha);
            p.setSexo(sexo);
            p.setDisciplina1(disciplina1);
            p.setDisciplina2(disciplina2);
            p.setContato(contato);
            p.setEmail(email);
            p.setLicenciatura(licenciatura);
            p.setBacharelado(bacharelado);
            p.setEspecializacao(especializacao);
            p.setMestrado(mestrado);
            p.setDoutorado(doutorado);
            p.setPosdoutorado(posdoutorado);
            p.setCurriculo(curriculo);
            p.setDiretordeturma(diretordeturma);
            
            sql.Inserir_Professor(p);
            Conexao.FecharConexao(con);
            
            Nome.setText("");
            Login.setText("");
            Senha.setText("");
            Sexo.setText("");
            Disciplina1.setText("");
            Disciplina2.setText("");
            Contato.setText("");
            Email.setText("");
            Licenciatura.setText("");
            Bacharelado.setText("");
            Especializacao.setText("");
            Mestrado.setText("");
            Doutorado.setText("");
            Posdoutorado.setText("");
            Curriculo.setText("");
            Diretordeturma.setText("");
            
            JOptionPane.showMessageDialog(null, "Professor cadastrado com sucesso.","QSys", JOptionPane.INFORMATION_MESSAGE );
            dispose();
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        if(Nome.equals("") || Login.equals("") || Senha.equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar vazio.","QSys", JOptionPane.WARNING_MESSAGE);
        }else{
            Connection con = Conexao.AbrirConexao();
            ProfessorDAO sql = new ProfessorDAO(con);
            Professor p = new Professor();
            
            p.setCodigo(CodigoProfessor);
            p.setNome(Nome);
            p.setLogin(Login);
            p.setSenha(Senha);
            
            //sql.Alterar_Professor(p);
            Conexao.FecharConexao(con);
            
            CodigoProfessor.setText("");
            Nome.setText("");
            Login.setText("");
            Senha.setText("");
            
        }
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        if(Nome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo ''Código do professor'' com seu respectivo código para consultá-lo.");
        }
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Assunto;
    private javax.swing.JTextField Bacharelado;
    private javax.swing.JTextField CodigoProfessor;
    private javax.swing.JTextField Contato;
    private javax.swing.JTextPane Curriculo;
    private javax.swing.JTextField Diretordeturma;
    private javax.swing.JMenu Disciplina;
    private javax.swing.JTextField Disciplina1;
    private javax.swing.JTextField Disciplina2;
    private javax.swing.JTextField Doutorado;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Especializacao;
    private javax.swing.JLabel Fundo;
    private javax.swing.JTextField Licenciatura;
    private javax.swing.JTextField Login;
    private javax.swing.JTextField Mestrado;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Posdoutorado;
    private javax.swing.JMenu Professor;
    private javax.swing.JMenu Prova;
    private javax.swing.JMenu Questão;
    private javax.swing.JMenu Sair;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JTextField Sexo;
    private javax.swing.JMenu Sobre;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtBacharelado;
    private javax.swing.JLabel txtCodigoProfessor;
    private javax.swing.JLabel txtContato;
    private javax.swing.JLabel txtDiretordeturma;
    private javax.swing.JLabel txtDisciplina;
    private javax.swing.JLabel txtDoutorado;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtEspecializacao;
    private javax.swing.JLabel txtLicenciatura;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtMestrado;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPosdoutorado;
    private javax.swing.JLabel txtSenha;
    private javax.swing.JLabel txtSexo;
    private javax.swing.JLabel txtTitulacoes;
    // End of variables declaration//GEN-END:variables

    private void setNome(String nome) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSenha(String senha) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setLogin(String login) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setNome(JTextField Nome) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSenha(JPasswordField Senha) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setLogin(JTextField Login) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setCodigo(JTextField CodigoProfessor) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSexo(String sexo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDisciplina1(String disciplina1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDisciplina2(String disciplina2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setContato(String contato) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setEmail(String email) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setLicenciatura(String licenciatura) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setBacharelado(String bacharelado) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setEspecializacao(String especializacao) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setMestrado(String mestrado) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDoutorado(String doutorado) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setPosdoutorado(String posdoutorado) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setDiretordeturma(String diretordeturma) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setCurriculo(String curriculo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
