/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author XPerience
 */
public class Sobre extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Sobre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Texto4 = new javax.swing.JLabel();
        Texto5 = new javax.swing.JLabel();
        Texto6 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        Professor = new javax.swing.JMenu();
        Assunto = new javax.swing.JMenu();
        Disciplina = new javax.swing.JMenu();
        Questão = new javax.swing.JMenu();
        Prova = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();
        Sair = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sobre o QSys");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 339));
        jPanel1.setLayout(null);

        Titulo.setFont(new java.awt.Font("Stencil FourReversed", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("QSys");
        jPanel1.add(Titulo);
        Titulo.setBounds(20, 90, 120, 50);

        Texto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto1.setForeground(new java.awt.Color(255, 255, 255));
        Texto1.setText("Esse é o sistema QSys, desenvolvido para ser capaz de manter professores, disciplinas, assuntos e questões em um banco de dados.");
        jPanel1.add(Texto1);
        Texto1.setBounds(20, 140, 820, 17);

        Texto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto2.setForeground(new java.awt.Color(255, 255, 255));
        Texto2.setText("O QSys também foi desenvolvido para gerar provas já cadastradas que podem ser impressas na extensão .pdf. O desenvolvimento");
        jPanel1.add(Texto2);
        Texto2.setBounds(20, 160, 820, 20);

        Texto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto3.setForeground(new java.awt.Color(255, 255, 255));
        Texto3.setText("de um sistema feito em java foi proposto pelo professor da escola EEEP Antônio Rodrigues de Oliveira, Claudiano \"Cláudio\" Matias, na");
        jPanel1.add(Texto3);
        Texto3.setBounds(20, 180, 810, 20);

        Texto4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto4.setForeground(new java.awt.Color(255, 255, 255));
        Texto4.setText("disciplina Laboratório de Software, para o primeiro semestre de 2017 na turma de 3º ano Informática, tendo como membro gerente ");
        jPanel1.add(Texto4);
        Texto4.setBounds(20, 200, 830, 20);

        Texto5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto5.setForeground(new java.awt.Color(255, 255, 255));
        Texto5.setText("Alexsandro Souza (nº 1) e equipe, Antonio \"Tonhão\" Mateus (nº 7), Edemara Rodrigues (nº 10) e Naiara Moreira (nº 30). O trabalho");
        jPanel1.add(Texto5);
        Texto5.setBounds(20, 220, 820, 20);

        Texto6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Texto6.setForeground(new java.awt.Color(255, 255, 255));
        Texto6.setText("produzido em quatro meses - de Fevereiro a Junho. Um projeto obviamente árduo, porém indiscutivelmente divertido.");
        jPanel1.add(Texto6);
        Texto6.setBounds(20, 240, 750, 20);

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoVoltar);
        botaoVoltar.setBounds(400, 413, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sobreFundo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -6, 860, 470);

        Professor.setText("Professor");
        Professor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfessorMouseClicked(evt);
            }
        });
        jMenuBar3.add(Professor);

        Assunto.setText("Assunto");
        Assunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssuntoMouseClicked(evt);
            }
        });
        jMenuBar3.add(Assunto);

        Disciplina.setText("Disciplina");
        Disciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisciplinaMouseClicked(evt);
            }
        });
        jMenuBar3.add(Disciplina);

        Questão.setText("Questão");
        Questão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuestãoMouseClicked(evt);
            }
        });
        jMenuBar3.add(Questão);

        Prova.setText("Prova");
        Prova.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProvaMouseClicked(evt);
            }
        });
        jMenuBar3.add(Prova);

        Sobre.setText("Sobre");
        Sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SobreMouseClicked(evt);
            }
        });
        jMenuBar3.add(Sobre);

        Sair.setText("Sair");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar3.add(Sair);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void SobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SobreMouseClicked
        JOptionPane.showMessageDialog(null, "Você já está nessa janela.");
    }//GEN-LAST:event_SobreMouseClicked

    private void ProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfessorMouseClicked
        
    }//GEN-LAST:event_ProfessorMouseClicked

    private void AssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssuntoMouseClicked
        Assunto assunto = new Assunto();
        assunto.setVisible(true);
        dispose();
    }//GEN-LAST:event_AssuntoMouseClicked

    private void DisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisciplinaMouseClicked
        Disciplina disciplina = new Disciplina();
        disciplina.setVisible(true);
        dispose();
    }//GEN-LAST:event_DisciplinaMouseClicked

    private void QuestãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuestãoMouseClicked
        Questão questão = new Questão();
        questão.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuestãoMouseClicked

    private void ProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProvaMouseClicked
        Prova prova = new Prova();
        prova.setVisible(true);
        dispose();
    }//GEN-LAST:event_ProvaMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        dispose();
    }//GEN-LAST:event_SairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sobre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Assunto;
    private javax.swing.JMenu Disciplina;
    private javax.swing.JMenu Professor;
    private javax.swing.JMenu Prova;
    private javax.swing.JMenu Questão;
    private javax.swing.JMenu Sair;
    private javax.swing.JMenu Sobre;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    private javax.swing.JLabel Texto5;
    private javax.swing.JLabel Texto6;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
